### ISSUE TITLE
Logging: HTTP event has path and method at the parent level

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway#278] opened 2017-08-12 23:27 UTC
<img width="1440" alt="screen shot 2017-08-12 at 4 15 40 pm" src="https://user-images.githubusercontent.com/2752551/29244873-3dbe57e2-7f7a-11e7-9ba7-00f284094b50.png">

The `path` and `method` should be in the `http` event's `data`.  In the screenshot, they are in the outer log envelope for some reason.

**Comment by mthenw** [comment] 2017-08-14 09:40
Duplicate of https://github.com/serverless/event-gateway/issues/273

**Closed by mthenw** 2017-08-14 09:40 UTC
