### ISSUE TITLE
How to deploy the Event Gateway?

### ISSUE THREAD

**Issue by gunar** [serverless/event-gateway#299] opened 2017-08-18 06:00 UTC
I know `sls run` runs it locally,
and I can `sls deploy` the functions,
but how can I actually deploy the Event Gateway itself?

Thanks in advance.

**Comment by gunar** [comment] 2017-08-18 06:14
Oh, [it's not implemented yet](https://github.com/serverless/event-gateway-example/blob/master/README.md#deploy).

I've misread the release notes.
Calling it a beta version might have misled me.
This is feedback that docs could be more explicit about it.
Spent a whole bunch of time trying to figure this out.

On the bright side, looking very much forward to it!

**Comment by mthenw** [comment] 2017-08-18 20:35
@gunar thanks for your feedback! Yup, we definitely need to explain it more clearly in the README.

You can deploy, configure (via config API) and use event gateway right now. The issue is that `serverless run` doesn't support remote event gateway so you will not benefit from the framework integration. But still, EG can be used without that. But just to be clear, it's not yet ready for production.

**Comment by gunar** [comment] 2017-08-18 22:16
@mthenw oh, that's awesome! How would I go about deploying EG then?

**Comment by yunspace** [comment] 2017-08-20 11:44
@gunar the event-gateway is a simple golang binary which you should be able to deploy to whatever environment you choose as per https://github.com/serverless/event-gateway/blob/master/docs/developing.md

There is also a Dockerfile https://github.com/serverless/event-gateway/blob/master/Dockerfile if you wish to deploy to a Docker orchestrator. However as of now I haven't seen any official repos on docker hub, so you might need to build your own image.

**Comment by rupakg** [comment] 2017-08-20 16:05
As far as Docker is concerned, we are looking at creating an official repo on DockerHub soon.

**Comment by damianesteban** [comment] 2017-08-20 18:46
Would it be possible to integrate this with AWS API Gateway?

**Comment by mthenw** [comment] 2017-08-21 10:52
@yunspace thanks for the explanation!

@damianesteban what would be the use case? Could you tell more about it? EG can be replacement for API Gateway as it enabled exposing HTTP endpoint (HTTP subscription).

**Comment by damianesteban** [comment] 2017-08-21 17:14
@mthenw if it can be a full replacement then maybe there isn't much of a need - I'm just thinking in terms of existing infrastructure and ease of integration with cognito, etc.

**Comment by mthenw** [comment] 2017-08-22 11:38
@damianesteban gotcha. Our goal is not to be a full replacement for API Gateway and we are not planning to have feature parity with it. There is a lot of services across provider and supporting all of them is impossible.

We are planning to implement plugin system (https://github.com/serverless/event-gateway/issues/147) that allows creating plugins in different languages and that allows integrating EG with different services.

**Comment by yunspace** [comment] 2017-08-22 13:15
@mthenw I think it's worth noting that the vision behind this product is to span multiple cloud providers and potentially avoid vendor lock in. In terms of authentication (cognito) I did notice the serverless platform beta is using auth0.

**Comment by damianesteban** [comment] 2017-08-23 22:44
@mthenw - that sounds great. Having plugins is a great solution.

@yunspace - absolutely, and I'm all about avoiding vendor lock in. Having said that, the vast majority of developers that I've spoken with that are using the serverless framework are using it in conjunction with AWS API Gateway. I'm sure that will change over time. I would love to check out the serverless platform beta and see how it is setup - my team is starting a new project soon and we plan on going with serverless.

**Comment by mthenw** [comment] 2017-08-24 15:19
I gonna close this issue. There is another one regarding technical details of setting up production cluster https://github.com/serverless/event-gateway/issues/264. 

Feel free to ask more questions in separate issues!

**Closed by mthenw** 2017-08-24 15:19 UTC
Labels: kind/docs
